import os
import ast
import re
import subprocess
import glob
import shutil


class InterpreterNode:
    """
    Executes Manim scripts with automatic self-healing.
    If rendering fails, the CodeFixerAgent attempts to repair the code
    and re-run the scene up to a specified number of attempts.
    
    Also tracks rendered videos and merges them into a final output.
    """

    def __init__(self, fixer=None):
        self.fixer = fixer

    def _get_fixer(self):
        if self.fixer is None:
            from agents.codefixer_agent import CodeFixerAgent
            self.fixer = CodeFixerAgent()
        return self.fixer

    # ----------------------------------------------------------------------
    # Scene detection
    # ----------------------------------------------------------------------
    def _detect_scene_names(self, code: str):
        """
        Detect top-level classes that inherit from Scene.
        Returns a list of class names.
        """
        try:
            tree = ast.parse(code)
        except SyntaxError:
            pattern = r"^\s*class\s+([A-Za-z0-9_]+)\s*\(([^)]*Scene[^)]*)\)\s*:"
            return [m[0] for m in re.findall(pattern, code, flags=re.MULTILINE)]

        scene_names = []
        for node in tree.body:
            if not isinstance(node, ast.ClassDef):
                continue
            for base in node.bases:
                base_name = self._base_name(base)
                if base_name == "Scene" or base_name.endswith(".Scene"):
                    scene_names.append(node.name)
                    break
        return scene_names

    def _base_name(self, node) -> str:
        if isinstance(node, ast.Name):
            return node.id
        if isinstance(node, ast.Attribute):
            parent = self._base_name(node.value)
            return f"{parent}.{node.attr}" if parent else node.attr
        return ""

    def _validate_code(self, code: str):
        try:
            ast.parse(code)
        except SyntaxError as e:
            return False, f"SyntaxError: {e}"
        if not self._detect_scene_names(code):
            return False, "No Scene classes found"
        return True, ""

    # ----------------------------------------------------------------------
    # Audio Mixin setup
    # ----------------------------------------------------------------------
    def _copy_audio_mixin(self, output_dir: str):
        """Copy AudioMixin to the output directory so the script can import it."""
        source_path = os.path.join(os.path.dirname(__file__), "audio_mixin.py")
        dest_path = os.path.join(output_dir, "audio_mixin.py")
        
        if os.path.exists(source_path):
            shutil.copy2(source_path, dest_path)
            print(f"[Setup] Copied audio_mixin.py to {output_dir}")
            return True
        else:
            print(f"[Warning] audio_mixin.py not found at {source_path}")
            return False

    # ----------------------------------------------------------------------
    # Video file tracking
    # ----------------------------------------------------------------------
    def _find_scene_video(self, media_dir: str, script_name: str, scene_name: str, quality: str = "480p15"):
        """
        Locate the video file generated by Manim for a specific scene.
        Manim saves to: <media_dir>/videos/<script_name>/<quality>/<scene_name>.mp4
        """
        # Primary location (should always be here with --media_dir flag)
        primary_path = os.path.join(media_dir, "videos", script_name, quality, f"{scene_name}.mp4")
        
        if os.path.exists(primary_path):
            return primary_path
        
        # Fallback: search recursively in media_dir
        search_pattern = os.path.join(media_dir, "**", f"{scene_name}.mp4")
        matches = glob.glob(search_pattern, recursive=True)
        
        if matches:
            return matches[0]
        
        print(f"[Warning] Could not find video for {scene_name}")
        print(f"  Expected at: {primary_path}")
        return None

    def _write_attempt_logs(self, debug_dir: str, scene_name: str, attempt: int, result):
        if not debug_dir:
            return
        os.makedirs(debug_dir, exist_ok=True)
        safe_scene = re.sub(r"[^A-Za-z0-9_]+", "_", scene_name)
        base = os.path.join(debug_dir, f"{safe_scene}_attempt_{attempt}")
        with open(base + ".stdout.txt", "w", encoding="utf-8") as f:
            f.write(result.stdout or "")
        with open(base + ".stderr.txt", "w", encoding="utf-8") as f:
            f.write(result.stderr or "")

    # ----------------------------------------------------------------------
    # Video merging
    # ----------------------------------------------------------------------
    def _merge_videos(self, video_paths: list, output_path: str):
        """
        Merge multiple video files into one using ffmpeg concat.
        
        Args:
            video_paths: List of paths to video files
            output_path: Path where the merged video should be saved
        """
        if not video_paths:
            print("[Merge] No videos to merge.")
            return None
        
        if len(video_paths) == 1:
            # If only one video, just copy it
            shutil.copy2(video_paths[0], output_path)
            print(f"[Merge] Single video copied to: {output_path}")
            return output_path
        
        # Create a temporary file list for ffmpeg concat
        concat_file = output_path + ".concat.txt"
        try:
            with open(concat_file, "w", encoding="utf-8") as f:
                for video_path in video_paths:
                    # ffmpeg concat requires absolute paths
                    abs_path = os.path.abspath(video_path)
                    f.write(f"file '{abs_path}'\n")
            
            # Run ffmpeg concat
            result = subprocess.run(
                [
                    "ffmpeg", "-f", "concat", "-safe", "0",
                    "-i", concat_file,
                    "-c", "copy",  # Copy streams without re-encoding
                    "-y",  # Overwrite output file if exists
                    output_path
                ],
                capture_output=True,
                text=True
            )
            
            if result.returncode == 0:
                print(f"[Merge] Successfully merged {len(video_paths)} videos to: {output_path}")
                return output_path
            else:
                print(f"[Merge Error] {result.stderr}")
                return None
        
        except Exception as e:
            print(f"[Merge Error] Failed to merge videos: {e}")
            return None
        
        finally:
            # Clean up concat file
            if os.path.exists(concat_file):
                os.remove(concat_file)

    # ----------------------------------------------------------------------
    # Copy intermediate files
    # ----------------------------------------------------------------------
    def _organize_outputs(self, rendered_videos: list, output_dir: str, final_dir: str, file_name: str):
        """
        Organize rendered videos:
        1. Copy individual scene videos to output_dir
        2. Create merged video in final_dir
        
        Returns:
            dict with paths to organized files
        """
        organized = {
            "individual_scenes": [],
            "merged_video": None
        }
        
        # Copy individual videos to output directory
        for i, video_path in enumerate(rendered_videos):
            if video_path and os.path.exists(video_path):
                scene_name = os.path.basename(video_path)
                dest_path = os.path.join(output_dir, scene_name)
                shutil.copy2(video_path, dest_path)
                organized["individual_scenes"].append(dest_path)
                print(f"[Copy] Scene {i+1}: {dest_path}")
        
        # Merge videos into final output
        if organized["individual_scenes"]:
            final_video_path = os.path.join(final_dir, f"{file_name}_final.mp4")
            merged = self._merge_videos(organized["individual_scenes"], final_video_path)
            organized["merged_video"] = merged
        
        return organized

    # ----------------------------------------------------------------------
    # Core execution logic
    # ----------------------------------------------------------------------
    def run(self, code: str, file_name: str, output_dir: str, media_dir: str, final_dir: str = None, max_attempts: int = 3, debug_dir: str = None):
        os.makedirs(output_dir, exist_ok=True)
        os.makedirs(media_dir, exist_ok=True)
        if final_dir:
            os.makedirs(final_dir, exist_ok=True)
        if debug_dir:
            os.makedirs(debug_dir, exist_ok=True)
        
        # Copy AudioMixin so local import works
        self._copy_audio_mixin(output_dir)
        
        script_path = os.path.join(output_dir, f"{file_name}.py")

        # Ensure base imports exist
        if "from manim import" not in code:
            code = "from manim import *\nimport numpy as np\n\n" + code

        # Fix incorrect audio import
        code = code.replace(
            "from nodes.audio_mixin import AudioMixin",
            "from audio_mixin import AudioMixin"
        )

        # Write the script
        with open(script_path, "w", encoding="utf-8") as f:
            f.write(code)

        scene_names = self._detect_scene_names(code)
        if not scene_names:
            print("[Warning] No Scene classes found in the script.")
            return None

        rendered = []
        failed = []
        rendered_videos = []

        project_root = os.path.dirname(output_dir)

        scene_index = 0
        while scene_index < len(scene_names):
            scene_name = scene_names[scene_index]
            print(f"\n[Render] Starting {scene_name}...")
            scene_rendered = False
            for attempt in range(1, max_attempts + 1):
                try:
                    result = subprocess.run(
                        [
                            "manim",
                            "-ql",
                            "--disable_caching",
                            "--media_dir", os.path.abspath(media_dir),
                            os.path.abspath(script_path),
                            scene_name
                        ],
                        cwd=project_root,
                        text=True,
                        capture_output=True
                    )
                    self._write_attempt_logs(debug_dir, scene_name, attempt, result)

                    if result.returncode == 0:
                        print(f"[OK] {scene_name} rendered successfully.")
                        rendered.append(scene_name)
                        scene_rendered = True
                        
                        video_path = self._find_scene_video(media_dir, file_name, scene_name)
                        if video_path:
                            rendered_videos.append(video_path)
                            print(f"[Video] Found at: {video_path}")
                        else:
                            print(f"[Warning] Could not locate video for {scene_name}")
                        break

                    else:
                        print(f"[Error] {scene_name} failed (attempt {attempt}/{max_attempts}).")
                        print(result.stderr.strip())

                        with open(script_path, "r", encoding="utf-8") as f:
                            current_code = f.read()

                        try:
                            fixed_code = self._get_fixer().fix_code(current_code, result.stderr)
                            if not fixed_code.strip():
                                print("[Fixer Warning] Empty fix returned – skipping further attempts.")
                                break

                            valid, validation_error = self._validate_code(fixed_code)
                            if not valid:
                                print(f"[Fixer Warning] Invalid fix returned: {validation_error}")
                                break

                            with open(script_path, "w", encoding="utf-8") as f:
                                f.write(fixed_code)
                            if debug_dir:
                                safe_scene = re.sub(r"[^A-Za-z0-9_]+", "_", scene_name)
                                fixed_path = os.path.join(debug_dir, f"{safe_scene}_attempt_{attempt}_fixed.py")
                                with open(fixed_path, "w", encoding="utf-8") as f:
                                    f.write(fixed_code)

                            code = fixed_code
                            updated_scene_names = self._detect_scene_names(code)
                            if updated_scene_names:
                                scene_names = updated_scene_names
                            print("[Auto-fix] CodeFixerAgent applied. Retrying...")

                        except Exception as fix_error:
                            print(f"[Fixer Error] Failed to apply fix: {fix_error}")
                            break

                except Exception as e:
                    print(f"[System Error] Could not execute Manim for {scene_name}: {e}")
                    break

            if not scene_rendered:
                print(f"[Failure] Could not render {scene_name} after {max_attempts} attempts.")
                failed.append(scene_name)
            scene_index += 1

        print("\n--- Rendering Summary ---")
        print(f"Successful: {len(rendered)} scene(s): {rendered}")
        print(f"Failed: {len(failed)} scene(s): {failed}\n")

        # Organize outputs
        organized = {}
        if final_dir and rendered_videos:
            print("\n[Organization] Copying and merging videos...")
            organized = self._organize_outputs(rendered_videos, output_dir, final_dir, file_name)
            
            if organized.get("merged_video"):
                print(f"\nFinal merged video: {organized['merged_video']}")
            
            print(f"Individual scenes saved in: {output_dir}")

        return {
            "script_path": script_path,
            "rendered": rendered,
            "failed": failed,
            "scenes": rendered + failed,
            "video_files": rendered_videos,
            "organized": organized
        }
